language: node_js # 设置语言

node_js: stable # 设置相应版本

env:
  global:
    - GH_REF=github.com/org-cjl/blogs.git
    - secure: "j/yh1TdtZO43AnnHS7yxpUECyess6qrhe8vvl2JGtt9JciITy1ItIbLXm/gjlZitfJBFOlMX0D/0knddO+zwSrxvGnSulWbAkmnlNVf/vbQRlrBRXlELD4j5a3tDrct5430O5kj/t+y4Wg/WQRT99YH/7I6v+yNCW5I68mMn4FgFgO+EA3AIu5kZOmMKs+1Fsd3lU16/vOd5px0PTgN6K9+Auffr7fFmapVODIT7RCfkiN6vvVLU0LJmqboyks4CjIWNggmDZJLylsy/GR31UabCdH2omjwLcDM/FueT3C//oTIPqTygursXQ+edxtWnqSEDjjv31L/Qg9GcX8fnfNc8YzMbs/oHRDstx4qDC1rWWByewnl103GNK11bOcQvn5oY0mkpo88fpKDwa+cVzFoEcSsy30ZxIss/EnH66tOhcZr7QaCaG/o6QBbkEGEFMEr2mPezIJ83Bso1YOuLv4cPFrPf4qG5bI0MbqzExhFWczZGgpsOwOHVx3OekIb1bvcXXGYRZ+dNjQLWYsY2hbfYRn0PF69NqnA4cjDl5VazDD1tMAAaE8xFlol9AW1X8pUEfnrgMpI6E+6rMYwihEtxuknGpw+c3Fn5JQpvLok/kNMR5gmyUkiFsseCPxN80iYID2D+myLeuX1G4zhsfckF30Gw2mWotWtQLu9nVKU="
#    - secure: "AALO01UcqJ5SGXsv5nw3Y+PNnDRpXp3SxFDcAD+OSZFXCaO2inwisr0UrFfYNZOs9b48WLjcvx0ui59SvYjdArFPY3ykvPLCwG/sgc2Ru66LboRjON7SRcBwqSotu95ouWcvCcy1FYKDpKiMIOdU3hodkKtjGyxrg6HmdssM0VkDjRiB9Qm09IPZRlnfhMiqtJyeqJRfb6zdhTMJvivkimo251l7/sykrwIit0n0aZL+Hm6O/gw2XfFrIk8v3QEgKY5o4Z0yUbsgwB4Knzpl/0Gl1d2+VVPgsXvvatNvyv8RPQQijwoTUdlb+0hPLKmDmrKmmFHHVido1Pcfg5tiB3fhJQMMbCbdjVBATs+XOqi7+AXn7yFtrWLu0CVU51hwfZ9xT/m+54IaMva/pdxECJPni4EYx3mOza8YfZc57YBs2x8GNWeC98aMpLM0zF+vXDHegOTtqNIXejdfHkSYA9/PIaTgBW9IoTYzfCOgS2gtV2MhGxuaGEhRQgLhtHmqdmu/0Szh44m7jAaDd2RkPDtUzgjkZ2aOa+5sub6xDJLAESK4X/LpkbUp/tRZUwP5F3iLANQwCFIUHJhXh/vIF/sGbHeGqzO2tmL1fF9f9Xh5GnkdPtBvlV+UIFC3jF6pu40aNMFjIsW0x/NoYZsOEhI1eP1i6Y9ekLELRoH/ogc="
  
branches:
  only:
    - blog-source #只监测博客源码分支(md文件)

# S: Build Lifecycle

install:
  - npm install # 安装hexo及插件

before_script:
  # 替换同目录下的_config.yml文件中github_token字符串为travis后台刚才配置的变量，注>意此处sed命令用了双引号。单引号无效！
  # - sed -i "s/GH_TOKEN/${GH_TOKEN}/g" _config.yml || exit 1

script:
  - hexo clean # 清除
  - hexo d -g # 生成

after_script:
  - cd ./public
  - git init
  - git config user.name "caojialin" # 修改name
  - git config user.email "caojialin2017@gmail.com" # 修改email
  - git config core.quotepath false  # 去除引号
  - git add .
  - git commit -m "Travis CI Auto Build"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages # GH_TOKEN是在travis加密github中配置token的secure

# E: Build LifeCycle
    
